language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: IA/aodEKthXf2zjSlHB7RIHp8mxOR4xgh9aQGR0lEVQMy4LRSu/qH/Vvd3m9bJWxzQgSY+YCACVZXmDjq0VpgzFq36AqsFxYErMb9ljG784LmdRwYa3u4AdpyLAEePhWtIrmYmTAiK/W7zUqqVLmRfRP7tYRy9jmI3gNRqX2lK519Ex6K91/C14zZg+05gv9D9q6VMefpgoRILS/rQx5kQNSuJ/R2LvD2cO/UwQqDItx8ilnHyANdJ6/QTzApwv1bdr9gWPVFj2NHT4NEo60jA/r4aH4wB8n7oyiyFw9taGE4uO2OOM5pBDyZ3f/Fpv/SpMvVmyNFE4Yj7fH6NqwkCRTwO53O+38e2MiDNb7rBG1HpetrAWmeSjSjhBhgvgNVTjM7P3vw44goQzbw+Z3fQ1n/BEIoT8ZEXunYviPfA37BNOEKBH0wspoknOWuupyLmIjVLlw6fiAeXlpZFATit6lMs+gH9dhuuGU8VUQ3lkIxmaQhQU7mxt7O08K8aUWLP0BYZ89IkMpN2i6V5+yskegkgr2pVVimgvG8FdKPqcIFWHgBXxJ+qpAVbBUtMnvArkqwPUFo80WM89UBcRvS1YHNurPpqLEN3C+dhfdIt+NbSFovP6Bs4OW+tVk9SUlMc3nqxpW0EE8LsCRCvTAFgyvp96mF84OAtYi9XZwUiE=
  app: react-hot-cold
  on:
    repo: adrianasu/react-hot-cold
