language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: cK4tsJsLYt4fr6WXAppRx6J6sDXCFwU+VyQ8Qy4/6Jgmyv7t6MIkwDApEug7odEtwmiOmd9FcfcoIIsT/Ywmzg8zhkdRTGEfatiuPYinKv0LYd9JJ8/0nFKMcO5zYN/Bs88SDOCga0J44msdWEahRZEbh084+v8vmUdPV+lPgjyv/bX/8ipo8N19fg7jCBqdSVJ1AuHLIoCvjC5yqvPHElr3evmhm1VqqE7MdRBMoWI1PJvaVI3Z6AZ6UiOD7vFDmcJBt05wjRCNr8zmFC1ueXHPDH06gySE2yWZmimmIZ/BQjhIW2QkjzsF2E26ylIb/4xEE8Dda2y0RACilGMcaGc+Vc7XlVKaW/xmRj1jI2EHy7e7oo/seBb5iNbL11PPFudNCBIoWC79ljtHzh9ZLUFe8FMySwgqDIYtycKMPkJnBUkh3iL2asenk+fWQAUL6VsS7GFLUK7QS3wHBhkedMKmpDX+2Hwlvw3ihN81bvnSydrc9SyLrUhdNYw2n1LfIqXUJXn5A0fwj4od3zx/476d/4WHLC+JFEqwbQ6a5gc9geR+B5zj/1fpza0nMTNHI8LlmOPsuqEjfR7Xj2/fH06sTU3o+tmYUzS8u7Gr+4KWN3MZz4lDnUphWYwVcvdo2Gs9WtLwwIvm0VFUEWH+dw527ApdU976ljhTEZ6oc5E=
  app: react-hot-cold
  on:
    repo: adrianasu/react-hot-cold
